NXP-21851 AWS REKOGNITION
nuxeo/nuxeo-vision pull request #8
Opened 2017-03-13 03:32 UTC by michaelva

2017-03-13 03:32 UTC, nuxeojenkins commented
From the blame information on this pull request, potential reviewers: @ThibArg

2017-03-13 03:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nuxeo/nuxeo-vision?pullRequest=8) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/nuxeo/nuxeo-vision?pullRequest=8) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: loopingz<br/>:x: michaelva<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nuxeo/nuxeo-vision?pullRequest=8) it.</sub>

2017-03-13 03:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nuxeo/nuxeo-vision?pullRequest=8) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/nuxeo/nuxeo-vision?pullRequest=8) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: loopingz<br/>:x: michaelva<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nuxeo/nuxeo-vision?pullRequest=8) it.</sub>

2017-03-14 16:41 UTC, akervern requested changes
Also, ensure to format the whole code and fix your copyrights issues.

2017-03-14 16:41 UTC, akervern commented on nuxeo-vision-google/pom.xml
> +      <version>v1-rev2-1.21.0</version>
Set version in VersionManagement of the parent pom

2017-03-14 16:41 UTC, akervern commented on nuxeo-vision-google/src/main/resources/OSGI-INF/google-vision-provider.xml
> +  <require>org.nuxeo.vision.core.service</require>
No need to require a component when not overriding something; it seems it looks like a simple contribution here.

2017-03-14 16:41 UTC, akervern commented on nuxeo-vision-aws/src/main/resources/OSGI-INF/aws-rekognition-provider.xml
> +  <require>org.nuxeo.vision.core.service</require>
Same as Google Vision provider; no need to require a component for contributing to it

2017-03-14 16:41 UTC, akervern commented on nuxeo-vision-aws/src/test/java/org/nuxeo/vision/aws/test/TestAmazonRekognitionProvider.java
> + * (C) Copyright 2015-2016 Nuxeo SA (http://nuxeo.com/) and others.
2017?

2017-03-14 16:41 UTC, akervern commented on nuxeo-vision-core/src/main/java/org/nuxeo/vision/core/service/Vision.java
> +                           int maxResults) throws IOException, GeneralSecurityException;
Not our format standards

2017-03-14 16:41 UTC, akervern commented on nuxeo-vision-core/src/main/java/org/nuxeo/vision/core/service/VisionProvider.java
> +public interface VisionProvider {
From 9.1?

2017-03-14 16:41 UTC, akervern commented on nuxeo-vision-aws/src/main/java/org/nuxeo/vision/aws/AmazonRekognitionProvider.java
> +        // thread safe lazy initialization of the google vision client
Wrong comment?

2017-03-14 17:52 UTC, michaelva commented
@akervern made all the requested changes

2017-03-14 17:55 UTC, akervern approved these changes

2017-03-14 17:58 UTC, merged

2017-03-14 23:24 UTC, efge reviewed
Futher review.

2017-03-14 23:24 UTC, efge commented on nuxeo-vision-aws/src/main/java/org/nuxeo/vision/aws/AmazonRekognitionProvider.java
> +    protected static final List<String> SUPPORTED_FORMAT = ImmutableList.of("image/jpeg", "image/png");
No need to pull Guava's `ImmutableList` for that, `Arrays.asList("image/jpeg", "image/png")` works just as well.

Same in all other files.

2017-03-14 23:24 UTC, efge commented on nuxeo-vision-aws/src/main/java/org/nuxeo/vision/aws/AmazonRekognitionProvider.java
> +    protected static final long _5MB = 5242880;
Please don't use constants with an initial `_`. And name it according to its use: `BLOB_MAX_SIZE`.
Also write the value as `5*1024*1024` for clarity.

Same in GoogleVisionProvider etc.

2017-03-14 23:24 UTC, efge commented on nuxeo-vision-aws/src/main/java/org/nuxeo/vision/aws/AmazonRekognitionProvider.java
> +    private volatile AmazonRekognition client = null;
`private` -> `protected` to allow subclassing. Same in GoogleVisionProvider etc
`= null` is not needed so remove it.
Please add a comment explaining that it's `volatile` on purpose to allow for the double-checked locking idiom.

2017-03-14 23:24 UTC, efge commented on nuxeo-vision-aws/src/main/java/org/nuxeo/vision/aws/AmazonRekognitionProvider.java
> +        ArrayList<VisionResponse> result = new ArrayList<>();
`List<VisionResponse> result`

2017-03-14 23:24 UTC, efge commented on nuxeo-vision-aws/src/main/java/org/nuxeo/vision/aws/AmazonRekognitionProvider.java
> +    private Map<String, String> parameters;
`private` -> `protected`

2017-03-14 23:24 UTC, efge commented on nuxeo-vision-aws/src/main/java/org/nuxeo/vision/aws/AmazonRekognitionProvider.java
> +    private AmazonRekognition getClient() {
`private` -> `protected`

2017-03-14 23:24 UTC, efge commented on nuxeo-vision-aws/src/main/java/org/nuxeo/vision/aws/AmazonRekognitionResponse.java
> +    private List<TextEntity> labels = new ArrayList<TextEntity>();
`private` -> `protected`

2017-03-14 23:24 UTC, efge commented on nuxeo-vision-aws/src/test/java/org/nuxeo/vision/aws/test/TestAmazonRekognitionProvider.java
> +                ImmutableList.of(VisionFeature.LABEL_DETECTION), 5);
`ImmutableList.of` -> `Arrays.asList`

2017-03-14 23:24 UTC, efge commented on nuxeo-vision-core/src/main/java/org/nuxeo/vision/core/image/ColorInfo.java
> + * (C) Copyright 2017 Nuxeo SA (http://nuxeo.com/) and others.
Keep the initial year of the range, and `Nuxeo SA` -> `Nuxeo`.

2017-03-14 23:24 UTC, efge commented on nuxeo-vision-core/src/main/java/org/nuxeo/vision/core/operation/VisionOp.java
> +            if (provider == null || provider.length() == 0) {
`if (StringUtils.isEmpty(provider))`

2017-03-14 23:24 UTC, efge commented on nuxeo-vision-core/src/main/java/org/nuxeo/vision/core/service/Vision.java
> +     * @since 9.1
We usually put the `@since` tag at the end of the Javadoc.

2017-03-14 23:24 UTC, efge commented on nuxeo-vision-core/src/main/java/org/nuxeo/vision/core/service/VisionImpl.java
> +                    | InvocationTargetException e) {
Use `ReflectiveOperationException` instead of the several individual subclasses of it to shorten this.

2017-03-14 23:24 UTC, efge commented on nuxeo-vision-core/src/main/java/org/nuxeo/vision/core/service/VisionProvider.java
> +    List<VisionResponse> execute(List<Blob> blobs, List<VisionFeature> features, int maxResults)
Please add a description of the method to the Javadoc (and in the other methods).

2017-03-14 23:24 UTC, efge commented on nuxeo-vision-core/src/main/java/org/nuxeo/vision/core/service/VisionProvider.java
> +public interface VisionProvider {
Please add text describing what this interface is about to the Javadoc.

2017-03-14 23:24 UTC, efge commented on nuxeo-vision-core/src/main/java/org/nuxeo/vision/core/service/VisionProviderDescriptor.java
> +    public Class getClassName() {
This returns a `Class` (actually should be a `Class<?>`, and the field too), so should be called `getKlass` (as `getClass` is reserved).

2017-03-14 23:24 UTC, efge commented on nuxeo-vision-google/src/main/java/org/nuxeo/vision/google/GoogleVisionProvider.java
> +        return path != null && path.length() > 0;
`return StringUtils.isNotEmpty(path)`
Same in other places in this file.

2017-03-14 23:24 UTC, efge commented on nuxeo-vision-marketplace/src/main/resources/install/templates/nuxeo-vision/nuxeo.defaults
> +org.nuxeo.vision.default.provider=google
This should have a newline at the end to avoid confusing editors.